# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sys-Proctitle
version:      0.02
version_from: lib/Sys/Proctitle.pm
installdirs:  site
requires:
    Class::Member:                 1.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
